---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Base big panda services
  hosts: base
  become: yes
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: img-panda, tags: img-panda }
    - { role: smart-panda, tags: smart-panda }
