---
- name: util-img-panda
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Base img panda services
  hosts: base
  become: yes
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: img-panda, tags: img-panda }
