---
- name: copy img-panda service
  copy: src=img-panda dest=/tmp/ owner=root group=root mode=755

- name: npm install
  npm: path=/tmp/img-panda
  
- name: configure img-panda service
  copy: src=etc/init/img-panda.conf dest=/etc/init/ owner=root group=root mode=644
  
- name: start img-panda service 
  service:
    name: img-panda
    state: started
 
