---
- name: copy smart-panda service
  copy: src=smart-panda dest=/tmp/ owner=root group=root mode=755

- name: npm install
  npm: path=/tmp/smart-panda
  
- name: configure smart-panda service
  copy: src=roles/smart-panda/files/smart-panda/smart-panda.conf dest=/etc/init/ owner=root group=root mode=644
  
- name: start smart-panda service 
 service:
    name: smart-panda
    state: started
 
